---
abstract: 'gearman casual'
author:
  - 'Tokuhiro Matsuno E<lt>tokuhirom AAJKLFJEF@ GMAIL COME<gt>'
build_requires:
  Gearman::Client: 0
  Test::More: 0.98
  Test::Requires: 0
  Test::TCP: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.4001, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Gearman-Glutch
no_index:
  directory:
    - inc
provides:
  Gearman::Glutch:
    file: lib/Gearman/Glutch.pm
    version: 0.02
requires:
  Class::Accessor::Fast: 0
  Gearman::Server: 0
  Gearman::Worker: 0
  parent: 0
  perl: 5.010001
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
